version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test

  adminer:
    image: adminer
    ports:
      - 8080:8080